### PR TITLE
fix: change redirection logic, to break out redirect loop

### LINKED ISSUE #3: If HTTP referer is set, do not redirect
We should not redirect the user, if HTTP referer is set, because the user is coming from somewhere and expect the URL he/she requested.

### PR DESCRIPTION
**Pull request by malteriechmann**
This will also fix #3

### CODE REVIEW

File: Classes/Middleware/LanguageRedirectionMiddleware.php [hunk 1]
```diff
@@ -12,25 +12,37 @@ class LanguageRedirectionMiddleware implements MiddlewareInterface
...
 
-        // Do nothing, if the website has only one configured language
+        // Do nothing, if the website has only one configured site language
         if (count($siteLanguages) === 1) {
             return $handler->handle($request);
         }
 
-        // Get the browser language from the HTTP request headers
-        $browserLanguageIsoCode = substr($request->getHeaderLine('Accept-Language'), 0, 2);
+        // Get the is code of the browser language from HTTP request header
```
Comment (Yanohd) [inline Classes/Middleware/LanguageRedirectionMiddleware.php:35]:
```suggestion
        // Get the code of the browser language from HTTP request header
```
